### ISSUE TITLE
Consider removing load balancing requirement

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#11]
During IETF 109, @martinthomson pointed out that this requirement cuts a little too much into the solution space. There seemed to be support for removing this (controversial) bit as part of the core requirements.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.
