### ISSUE TITLE
Non-requirement on IP address extraction

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#14]
The text says

`How packets are forwarded between the IP proxying connection and the physical network is out of scope. This is deliberately not specified and will be left to individual implementations.`

It's actually not really clear to me what this mean. Can you further explain?

**Comment by DavidSchinazi** [comment]
@mirjak One way this can be accomplished is using a TUN interface, but there are others way to do it, and we don't want to prescribe implementation details. Does that help?

**Comment by mirjak** [comment]
Okay that's makes sense. However, do we really need to list this as a non-requirement? If so, adding examples might help.

**Comment by DavidSchinazi** [comment]
To me, listing non-requirements is just as important as listing requirements. If you don't do that, you end up with infinite feature creep.

**Comment by achernya** [comment]
I'm a bit confused by the title of this issue versus the discussion. The title discusses IP *address* extraction, but the discussion is about physical network handling of the IP packets (e.g., with a TUN device or similar).

I'm not sure what sorts of examples can be added here. I'm open to including the text "Implementations can use technologies such as TAP/TUN devices, RAW sockets, or similar to accomplish this task." but it feels unnecessary for a requirements document.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.

**Comment by mirjak** [comment]
If this text is not about network handling as David indicated, then I still don't what the text is about (and obviously David also didn't understand it correctly) and it needed to be further explained, please!

**Comment by achernya** [comment]
@mirjak The text is about network handling; but the issue title you chose doesn't make sense to me. I believe @DavidSchinazi and I are on the same page here.

**Comment by mirjak** [comment]
Okay, looking at this again, this is clarified now in the document. However, I still don't see the point about having the non-requirement in the  document. How can this choice impact the protocol design? If there is no impact, I think we should still simply remove it.

**Comment by achernya** [comment]
I do not agree with the statement "If there is no impact, I think we should still simply remove it.". Like David, I think explicitly enumerating non-goals for the document is an important practice to avoid scope creep.

**Comment by mirjak** [comment]
I don't understand what the scope creep is in this case if there is no impact on the protocol. You could equally have a requirement that the layer 2 technology that is used underneath IP is out of scope but that would also not really be any helpful.
