### ISSUE TITLE
Document organisation: which requirement only apply to IP proxying (but not UDP proxying)?

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#15]
Most requirement listed actually equally apply to UDP proxying and IP proxying. I think it would be helpful to separate out those requirements that only apply to IP proxying and then have a more focused discussion about those.

**Comment by DavidSchinazi** [comment]
I don't see UDP proxying as relevant to this draft, why do you want to separate out requirements that happen to be met by CONNECT-UDP?

**Comment by mirjak** [comment]
Because I think only does that are specific to IP proxying are the ones that are interesting for discussion. For already other requirement we should simply do the same thing as we do for UDP proxying.

**Comment by DavidSchinazi** [comment]
I don't follow. This document discusses requirements for IP proxying. CONNECT-UDP has nothing to do with this.

**Comment by achernya** [comment]
I don't see an issue with the IP proxying and UDP proxying having similar, overlapping requirements documents. I would be more concerned about the final implementation/design documents if they contained redundant information.

**Comment by DavidSchinazi** [comment]
Closing this issue as CONNECT-UDP is not in scope for the draft-ietf-masque-ip-proxy-reqs.

**Comment by mirjak** [comment]
I didn't request to remove the requirements; I only asked to reorganise the document a bit because I think that would greatly help the discussion to focusing on those things which are IP specific. At least @kazuho made a similar comment in the jabber during the last session. I don't think he is aware of the discussion on this issue though. Please re-open the issue as I don't think we reached any conclusion here and should simply quickly discuss this at the next meeting to get more input.
