### ISSUE TITLE
Linking Requirements to the Use Cases with those requirements

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#2]
This draft contains a list of use cases (with descriptions) and a list of requirements (with descriptions). 

It isn't obvious to me which requirements come from which use cases. My suggestion would be to link each requirement to the use cases that require it.

One way to accomplish that, would be tagging each requirement with the section numbers/xrefs for the use cases that require it. Other ways would also work. 

My understanding is that the working group is still thinking about use cases, and it's possible/likely that some will be added, and even some use cases deleted. It will be much easier to maintain the list of requirements if we don't have to analyze all requirements each time we adjust the list of use cases that are considered in scope for IP proxying. 

This suggestion was made on the MASQUE mailing list during the adoption call for this draft. 

The adoption call mail thread starts at https://mailarchive.ietf.org/arch/msg/masque/cpcXQVBjpMQLbHMGpyAJCucEg3A/. I made the suggestion in https://mailarchive.ietf.org/arch/msg/masque/kG_BNeCShr98jXWC5MbjVjgHqH4/.

**Comment by DavidSchinazi** [comment]
While this would be a useful editorial change, we're not going to publish this document as an RFC so it's not worth the time required to make this change. I'm therefore closing this issue.
