### ISSUE TITLE
Route Negotiation requirement

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#25]
This requirement is still not fully clear to me. Can you maybe explain a bit more the scenario/use case where the peer needs this information about route changes mid-session? Is this really required in the base protocol?

**Comment by achernya** [comment]
An example scenario would be a network-to-network VPN. Imagine the case where you have two networks, A and B. The administrator of A adds subnet 1.2.3.0/24 and updates their routing announcements. For B to learn of this, there would need to be a provision for exchanging routing information over the protocol.

**Comment by mirjak** [comment]
I think this should be an extension for later or maybe even a separate protocol as this is only need for one specific use case.

**Comment by DavidSchinazi** [comment]
You can't proxy IP packets without knowing which packets should be proxied. You need routes for an IP-layer tunnel to work. This isn't a specific use-case, it's a fundamental property of an IP tunnel.

**Comment by achernya** [comment]
I propose closing this issue -- I believe this has been thoroughly addressed.

**Comment by mirjak** [comment]
That's a specific implementation detail and not a requirement.

**Comment by achernya** [comment]
@mirjak can you please elaborate? How is a fundamental property of an agreed-upon use case not a requirement?

**Comment by mirjak** [comment]
If the proxy is connected to the "open" Internet and not assumed to connect to "just" another network, it's not a requirement. So this is only needed for the x-to-network use cases but not for others.

**Comment by achernya** [comment]
I disagree. A proxy connected to the open internet has to advertise that it has a default route.

**Comment by gloinul** [comment]
So for the cases where a single endpoint borrows (or being assigned by the peer) an address or a set from the peer then that address comes out of an network that the peer controls and have routes. And that this address from the endpoint is similar to a case where the endpoint is on the same LAN as the peer. In that case you have very default rules when using this address. Thus any destination is either on this network, or its beyond the peer through the networks default gateway. Thus I don't see a need for route negotiation.

So I think there is a question what is the assumption of the proxying in different use cases. If you are VPN into a completely private network or into a network which has general connectivity. Is the thought here that this would be solved by basically advertising either just the private network x/24 for example or /0 for the second case?

**Comment by achernya** [comment]
Yes, if you want to provide a default advertising a /0 would solve the
case. For a corporate / split horizon network you'd advertise individual
subnets. Even in the individual flow case I think a route (or subset of
routes) is a useful property.

**Comment by chris-wood** [comment]
The chairs think #27 should be merged as editorial clarification. Issue #30 tracks the separate design question about whether or not route negotiation should be a requirement.
