### ISSUE TITLE
In Network to Network proxying, why does the MASQUE Server need a subnet address?

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#3]
Section 3.6: 

   Similarly, to support the network-
   to-network use case, the server will be able to request assignment of
   an IP address range from the client, and the client will either
   assign a range or decline the request.

Can you elaborate why the Server would need an IP address from the Client's network? The client will need to be a gateway in the client side network to be able to receive the traffic to forward, but I don't see why the server needs appear as that gateway?

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.
