### ISSUE TITLE
IP Assignment request

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#31]
The requirement on IP Assignment only specifies that the client or server can "request" an IP address (or range). However, for an VPN like use case it would be sufficient if the proxy just selects an address and tells the client. I think both cases should be covered in the requirement. This is proposed in PR #21

**Comment by DavidSchinazi** [comment]
Agreed, I've written up #32 to address this.

**Comment by mirjak** [comment]
Thanks for creating this PR. I think it would also be nice, if an address was assigned, to signal this to the peer. Can we also cover this in this requirement?

**Comment by DavidSchinazi** [comment]
@mirjak good point, done.
