### ISSUE TITLE
3.6.  Identity: Whay type of identity?

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#4]
B. Section 3.6:

I do understand the need for some identify. The server first of all to allow the client to determine it is communicating with the right MASQUE server. However for the identification of the client, is that likely at all to be a domain name? Isn't that a user name, or some other form of authorization to use the resource.

**Comment by achernya** [comment]
I think the client identity is free to be a username, token, email address, or some other identifier. As written, the text says "For example, [...] a fully-qualified domain name.".

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.
