### ISSUE TITLE
Section 3.8: Authorization requirements

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#5]
C. Section 3.8 in this context I think there are more than the MASQUE endpoint that needs authoriztion if network to network proxying would happen. Also, extension to OAUTH, doesn't that require work in another WG? It looks like more explanation of what the needs are that prompt the need for extending the authorization protocol.

**Comment by achernya** [comment]
I don't understand what you're asking for/suggesting here. Could you please elaborate what you mean when you say "more [...] that needs authorization"?

I do not believe there needs to be an extension to OAuth, so I do not see why work would be needed in another WG. The current text uses OAuth as a possible implementation of authentication. I see now in the draft text that OAuth looks much more mandatory than it is itnended to be, so I'm working on text to correct that.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.
