### ISSUE TITLE
Section 3.10: Flow control control surface

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#6]
I don't see an issue with a tunnel protocol being used without flow control. If one overwhelm either of the MASQUE client or server that is equal to congestion in the network. I think the question of flow control is a question of what mode the client want the QUIC tunnel to operate in depending on the path characteristics. In most cases I would assume an unreliable tunneling is sufficient, however over lossy links using QUIC as a reliability mechanism may be desired. I think one use case for this purpose that has been discussed in some circuits are for local repair between an endpoint in a local WIFI network, where the local network is connected to Internet over an satellite link. Local WIFI loses one like to retransmit over that local network, not end-to-end over a satellite path. In such a scenario one would need flow control as the retransmission buffering is not unlimited. So a question to the WG is if we actually need a control surface for which style of operation one are using?

**Comment by achernya** [comment]
Since MASQUE allows reliable streams and unreliable datagrams to be mixed within a single QUIC connection, I think the collection of MASQUE documents (but not necessary the IP Proxying requirements or its implementation) needs to provide guidance on flow control decisions and implications. I have personally been assuming thus far that providing control surfaces is a better option than being opinionated on it may unintentionally preclude use-cases unnecessarily.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.

**Comment by mirjak** [comment]
I saw that you added a section on "Reliable Transmission of IP Packets" in the extension part of the document. However, the section on Flow control is unmodified. Two points:

1) I'm not sure what the requirement on flow control actually requests. It says " guidance on how best to use flow control". As mentioned by others this is rather a matter of QUIC and I'm not sure what kind of guidance you are expecting the masque protocol?

2) I'm not sure if reliability support can only be an extension. If datagram is not supported in QUIC, would you rather fail the masque connection than using streams?

**Comment by DavidSchinazi** [comment]
Apologies for the lack of details, the text that was aimed at addressing this issue was the [Configuration of Congestion and Flow Control](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01#section-4.4) subsection.

**Comment by mirjak** [comment]
Ah, I missed that new section. That section makes sense for congestion control but not sure what it means for flow control. You don't need flow control if you don't buffer, however, if have a reliable transport you have to retransmit and then you need flow control and buffering. So the part that should be configurable is reliability (which is covered by 4.3).

My comments above still stand. In section 3.8 on flow control it is still not clear to me what the actually requirement here is. And I still think support of a reliable mode cannot just be optional in an extension. These points have not been addressed in the last revision.
