### ISSUE TITLE
Congestion Control on outer QUIC connection

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#7]
During IETF 108 there was some discussion about turning off congestion control under the assumptions that IP traffic is congestion controlled. This is something that generally have been considered as acceptable in IETF. However, if this is considered a requirements discussion of this should be added. As this might also require extension of QUIC itself to turn off congestion control for some QUIC streams or datagrams this require discussion.

**Comment by achernya** [comment]
@vasilvv likely has thoughts on this.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.
