### ISSUE TITLE
Indistingushible requirement

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#8]
I think a general VPN use would result in a traffic pattern that would be distinguishable from encrypted HTTPS Web traffic. Is only wire format the goal here? Some clarification would be desirable.

**Comment by achernya** [comment]
What sort of clarification would be helpful? The current text explicitly states "Traffic analysis is out of scope for this requirement.".

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.
