### ISSUE TITLE
Load balancing over multiple QUIC connections and servers?

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#9]
Do I interpret this section correctly that it requires a IP session to be split from a client to server over multiple QUIC connections or even two MASQUE servers? Especially if it is the later that is the case that will imply additional functionality for path selection on a sub IP session flow level to avoid reordering within such subflows. Even the first one can result in need for a reordering buffer in the server to ensure that traffic is forwarded without reordering.

Does this also need some additional concerns if someone deploys the servers under different networks, resulting in multi-homing scenarios where outgoing and returning traffic for sub-flows ends up in different paths? In general you will get some traffic steering concerns to deal with. 

To me this requirement appears to potentially imply quite a bit of more functionality to work.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.

**Comment by mirjak** [comment]
The scenario that the author have in mind is still not fully clear to me. Can you please further explain?

**Comment by DavidSchinazi** [comment]
Reopening, @achernya can you add some text to this subsection to clarify what the intent is?

**Comment by achernya** [comment]
The new text already includes

> This allows the IP proxying mechanisms to scale-out to multiple servers

Is this not clear @mirjak
